//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietDienThoai
    {
        public string IdMatHang { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> Gia { get; set; }
        public byte[] Anh { get; set; }
        public string ManHinh { get; set; }
        public string CamSau { get; set; }
        public string CamSelfie { get; set; }
        public string Ram { get; set; }
        public string BoNhoTrong { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string Pin { get; set; }
        public string Sim { get; set; }
        public string HeDieuHanh { get; set; }
        public string XuatXu { get; set; }
        public string NamRaMat { get; set; }
    
        public virtual MatHang MatHang { get; set; }
    }
}
