//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietLaptop
    {
        public string IdMatHang { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> Gia { get; set; }
        public byte[] Anh { get; set; }
        public string Manhinh { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string Ocung { get; set; }
        public string DoHoa { get; set; }
        public string HeDieuHanh { get; set; }
        public string KichThuoc { get; set; }
        public string TrongLuong { get; set; }
        public string XuatXu { get; set; }
        public string NamRaMat { get; set; }
    
        public virtual MatHang MatHang { get; set; }
    }
}
