//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public string MaNhaCungCap { get; set; }
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> GiaNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        public virtual CuaHang CuaHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
