//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiChinh
    {
        public string MaNguoiGop { get; set; }
        public string TenNguoiGop { get; set; }
        public Nullable<int> Von { get; set; }
        public Nullable<System.DateTime> NgayGopVon { get; set; }
        public string Email { get; set; }
        public string Nguon { get; set; }
    }
}
